version: '3'
services:
  frontend:
    build: ./client
    ports:
      - '3000:3000'
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URL=mongodb://mongo:27017/stack-ai
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
